## SigScale OCS Cluster StatefulSet
##
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ocs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ocs
  serviceName: otp
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ocs
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
      - name: ocs-chown
        image: sigscale/ocs
        stdin: true
        tty: true
        securityContext:
          runAsUser: 0
        command:
        - chown
        - otp:otp
        - db
        volumeMounts:
        - name: ocs-data
          mountPath: /home/otp/db
      - name: ocs-init
        image: sigscale/ocs
        env:
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: otp-dist
              key: ERLANG_COOKIE
        stdin: true
        tty: true
        command:
        - bash
        - "-c"
        - |
          set -e
          [[ `hostname --fqdn` =~ (^.*)-([0-9]+)?.(.*)$ ]] || exit 1
          hostbase=${BASH_REMATCH[1]}
          ordinal=${BASH_REMATCH[2]}
          domain=${BASH_REMATCH[3]}
          if [[ ${ordinal} -eq 0 ]]; then
            bin/initialize
          else
            bin/join ocs@${hostbase}-$((--ordinal)).${domain}
          fi
        ports:
        - name: epmd
          protocol: TCP
          containerPort: 4369
        - name: erl-rpc
          protocol: TCP
          containerPort: 54861
        volumeMounts:
        - name: ocs-data
          mountPath: /home/otp/db
      containers:
      - name: ocs
        image: sigscale/ocs
        env:
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: otp-dist
              key: ERLANG_COOKIE
        stdin: true
        tty: true
        ports:
        - name: epmd
          protocol: TCP
          containerPort: 4369
        - name: erl-rpc
          protocol: TCP
          containerPort: 54861
        - name: diameter-acct
          protocol: TCP
          containerPort: 3868
        - name: diameter-auth
          protocol: TCP
          containerPort: 3869
        - name: radius-auth
          protocol: UDP
          containerPort: 1812
        - name: radius-acct
          protocol: UDP
          containerPort: 1813
        - name: rest
          protocol: TCP
          containerPort: 8080
        - name: snmp
          protocol: UDP
          containerPort: 4161
        volumeMounts:
        - name: ocs-data
          mountPath: /home/otp/db
  volumeClaimTemplates:
  - metadata:
      name: ocs-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
