### ocs-init.yaml
###
### Claim a persistent disk, change owner to otp,
### initialize db, run ocs as deployment..
###
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ocs
  labels:
    app.kubernetes.io/name: ocs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ocs
  template:
    metadata:
      labels:
        app.kubernetes.io/name
    spec:
      initContainers:
      - name: ocs-chown
        image: sigscale/ocs
        stdin: true
        tty: true
        securityContext:
          runAsUser: 0
        command:
        - chown
        - otp:otp
        - db
        volumeMounts:
        - mountPath: /home/otp/db
          name: db
      - name: ocs-install
        image: sigscale/ocs
        command:
        - sh
        - bin/initialize
        volumeMounts:
        - mountPath: /home/otp/db
          name: db
      containers:
      - name: ocs
        image: sigscale/ocs
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /home/otp/db
          name: db
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: ocs-data
