### ocs-init.yaml
###
### Claim a persistent disk, change owner to otp,
### initialize db, run ocs as deployment..
###
apiVersion: v1
kind: Deployment
metadata:
  name: ocs
  labels:
    run: ocs
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ocs
  template:
    metadata:
      labels:
        run: ocs
    spec:
      initContainers:
      - name: ocs-chown
        image: sigscale/ocs
        securityContext:
          runAsUser: 0
        command:
        - chown
        - otp:otp
        - db
        volumeMounts:
        - mountPath: /home/otp/db
          name: db
      - name: ocs-install
        image: sigscale/ocs
        command:
        - sh
        - bin/initialize
        volumeMounts:
        - mountPath: /home/otp/db
          name: db
      containers:
      - name: ocs
        image: sigscale/ocs
        volumeMounts:
        - mountPath: /home/otp/db
          name: db
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: ocs-data
