## SigScale OCS DIAMETER Authentication Service
##
kind: Service
apiVersion: v1
metadata:
  name: diameter-auth
  labels:
    app.kubernetes.io/name: ocs
    oda.tmforum.org/componentName: sigscale-ocs
spec:
  selector:
    app.kubernetes.io/component: ocs-node
  ports:
  - protocol: TCP
    appProtocol: diameter
    port: 3869
    targetPort: diameter-auth
