## SigScale OCS REST Service
##
kind: Service
apiVersion: v1
metadata:
  name: sigscale-ocs-service
  labels:
    app.kubernetes.io/name: ocs
    oda.tmforum.org/componentName: sigscale-ocs
spec:
  selector:
    app.kubernetes.io/component: oam
  type: NodePort
  ports:
  - protocol: TCP
    appProtocol: http
    port: 8080
    targetPort: rest
