##
## Erlang/OTP Cluster Headless Service
##
kind: Service
apiVersion: v1
metadata:
  name: otp
  labels:
    oda.tmforum.org/componentName: sigscale-ocs
spec:
  selector:
    app.kubernetes.io/name: ocs
  type: ClusterIP
  clusterIP: None
