## SigScale OCS Cluster StatefulSet
##
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ocs
  labels:
    app.kubernetes.io/name: ocs
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ocs
  serviceName: otp
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ocs
        app.kubernetes.io/component: ocs-node
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: ocs-init
        image: asia.gcr.io/sigscale-ocs/ocs
        env:
        - name: ERLARGS
          value: ""
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: otp-dist
              key: ERLANG_COOKIE
        stdin: true
        tty: true
        command:
        - bash
        - "-c"
        - |
          set -e
          [[ `hostname --fqdn` =~ (^.*)-([0-9]+)?.(.*)$ ]] || exit 1
          hostbase=${BASH_REMATCH[1]}
          ordinal=${BASH_REMATCH[2]}
          domain=${BASH_REMATCH[3]}
          if [[ ${ordinal} -eq 0 ]]; then
            bin/initialize
          else
            bin/join ocs@${hostbase}-$((--ordinal)).${domain}
          fi
        ports:
        - name: epmd
          protocol: TCP
          containerPort: 4369
        - name: erl-rpc
          protocol: TCP
          containerPort: 54861
        volumeMounts:
        - name: ocs-data
          mountPath: /home/otp/db
      containers:
      - name: ocs
        image: asia.gcr.io/sigscale-ocs/ocs
        env:
        - name: ERLARGS
          value: ""
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: otp-dist
              key: ERLANG_COOKIE
        stdin: true
        tty: true
        ports:
        - name: epmd
          protocol: TCP
          containerPort: 4369
        - name: erl-rpc
          protocol: TCP
          containerPort: 54861
        - name: diameter-acct
          protocol: TCP
          containerPort: 3868
        - name: diameter-auth
          protocol: TCP
          containerPort: 3869
        - name: radius-auth
          protocol: UDP
          containerPort: 1812
        - name: radius-acct
          protocol: UDP
          containerPort: 1813
        - name: rest
          protocol: TCP
          containerPort: 8080
        - name: snmp
          protocol: UDP
          containerPort: 4161
        volumeMounts:
        - name: ocs-data
          mountPath: /home/otp/db
        - name: ocs-log
          mountPath: /home/otp/logs
        readinessProbe:
          httpGet:
            httpHeaders:
              - name: Accept
                value: application/health+json
              - name: Authorization
                value: Basic YWRtaW46YWRtaW4=
            path: /health
            port: rest
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 6
  volumeClaimTemplates:
  - metadata:
      name: ocs-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: ocs-log
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
