##
## Erlang/OTP Cluster Headless Service
##
kind: Service
apiVersion: v1
metadata:
  name: otp
  labels:
    app.kubernetes.io/name: ocs
spec:
  selector:
    app.kubernetes.io/component: ocs-node
  type: ClusterIP
  clusterIP: None
