## SigScale OCS RADIUS Accounting Service
##
kind: Service
apiVersion: v1
metadata:
  name: radius-acct
  labels:
    app.kubernetes.io/name: ocs
spec:
  selector:
    app.kubernetes.io/component: ocs-node
  ports:
  - protocol: UDP
    appProtocol: radius-acct
    port: 1813
    targetPort: radius-acct
